# FROM ghcr.io/rcwbr/release-it-docker-conv-changelog:0.1.0 TODO use semver image ref
FROM ghcr.io/rcwbr/release-it-docker-conv-changelog:main

COPY ./.release-it.json /.release-it.json
CMD [ "--config", "/.release-it.json" ]
