#!/bin/bash

set -e

git config --global --add safe.directory /github/workspace
git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
git config --global user.name github-actions[bot]
release-it $@ | tee $GITHUB_STEP_SUMMARY
