name: Release-it
author: Eric Weber (@rcwbr)
description: Release automation using release-it
# Potential workaround, see https://github.com/actions/runner/issues/2473
inputs:
  action_ref:
    default: ${{ github.action_ref }}
runs:
  using: docker
  image: docker://node:latest
  # image: docker://ghcr.io/rcwbr/release-it-action-core:${{ inputs.action_ref }}
  args:
    - "${{ inputs.action_ref }} --dry-run"
