name: PR workflow
on: [pull_request]
jobs:
  Build-Docker-Images:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker Buildx builder setup
        uses: docker/setup-buildx-action@v3
      -
        name: Docker Bake
        uses: docker/bake-action@v5
