name: Push workflow
on: [push]
jobs:
  release-it-prerelease:
    name: Release-it prerelease
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
      -
        name: Release-it
        # Include action by relative path to always use the current version
        uses: ./conventional-changelog-action
        with:
          release-it-extra-args: --dry-run --changelog
  release-it:
    name: Release-it
    runs-on: ubuntu-24.04
    # Run full release process for pushes to main
    # if: ${{ github.ref == 'refs/heads/main' }} TODO restore
    if: ${{ github.ref == 'refs/heads/1-define-initial-action' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
      -
        name: Release-it
        uses: ./conventional-changelog-action
