on:
  workflow_call:
    inputs:
      release-it-action:
        description: 'The release it action to use'
        default: 'rcwbr/release-it-action/conventional-changelog-action@0.1.0'
        required: false
        type: string
      default-branch:
        description: 'The branch from which to release on commit'
        default: 'refs/heads/main'
        required: false
        type: string
jobs:
  release-it-dry-run:
    name: Release-it dry-run
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      -
        name: Release-it
        # Include action by relative path to always use the current version
        uses: rcwbr/release-it-action/conventional-changelog-action@1-define-initial-action
        with:
          release-it-extra-args: --changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-it:
    name: Release-it
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    # Run full release process for pushes to main
    if: ${{ github.ref == inputs.default-branch }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      -
        name: Release-it
        uses: rcwbr/release-it-action/conventional-changelog-action@1-define-initial-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
