name: Release-it
on: [push]
jobs:
  release-it-prerelease:
    name: Release-it prerelease
    runs-on: ubuntu-24.04
    needs: [build-docker-images]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.7
      -
        name: Release-it
        # Include action by relative path to always use the current version
        uses: ./rcwbr/release-it-action/core
